name: "Using Deploy key Actions"
description: "Execute Git command using Deploy key"
author: "grandcolline"
inputs:
  cmd:
    required: true
    description: "The command you want to execute."
  dir:
    default: "."
    required: false
    description: "The relative path to execute command."
runs:
  using: "docker"
  image: "Dockerfile"
